# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(507, 762)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Calculator.sizePolicy().hasHeightForWidth())
        Calculator.setSizePolicy(sizePolicy)
        Calculator.setStyleSheet("QWidget {\n"
"    background-color: #1E1E1E;  /* Charcoal dark */\n"
"    color: #FFFFFF;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 16px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: #1E1E1E;  /* Charcoal dark */\n"
"    color: #FFFFFF;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 16px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(427, 600))
        self.stackedWidget.setStyleSheet("QWidget {\n"
"    background-color: #1E1E1E;  /* Charcoal dark */\n"
"    color: #FFFFFF;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 16px;\n"
"}")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page3 = QtWidgets.QWidget()
        self.page3.setStyleSheet("QWidget {\n"
"    background-color: #1E1E1E;  /* Charcoal dark */\n"
"    color: #FFFFFF;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 16px;\n"
"}")
        self.page3.setObjectName("page3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_flo = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_flo.sizePolicy().hasHeightForWidth())
        self.button_flo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_flo.setFont(font)
        self.button_flo.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_flo.setObjectName("button_flo")
        self.gridLayout_2.addWidget(self.button_flo, 8, 2, 1, 1)
        self.button_equal = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_equal.sizePolicy().hasHeightForWidth())
        self.button_equal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_equal.setFont(font)
        self.button_equal.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_equal.setObjectName("button_equal")
        self.gridLayout_2.addWidget(self.button_equal, 8, 3, 1, 1)
        self.button2 = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button2.sizePolicy().hasHeightForWidth())
        self.button2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button2.setFont(font)
        self.button2.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button2.setObjectName("button2")
        self.gridLayout_2.addWidget(self.button2, 7, 1, 1, 1)
        self.button_plus = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_plus.sizePolicy().hasHeightForWidth())
        self.button_plus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_plus.setFont(font)
        self.button_plus.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_plus.setObjectName("button_plus")
        self.gridLayout_2.addWidget(self.button_plus, 7, 3, 1, 1)
        self.button0 = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button0.sizePolicy().hasHeightForWidth())
        self.button0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button0.setFont(font)
        self.button0.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button0.setObjectName("button0")
        self.gridLayout_2.addWidget(self.button0, 8, 1, 1, 1)
        self.button3 = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button3.sizePolicy().hasHeightForWidth())
        self.button3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button3.setFont(font)
        self.button3.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button3.setObjectName("button3")
        self.gridLayout_2.addWidget(self.button3, 7, 2, 1, 1)
        self.button_pm = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_pm.sizePolicy().hasHeightForWidth())
        self.button_pm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_pm.setFont(font)
        self.button_pm.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_pm.setObjectName("button_pm")
        self.gridLayout_2.addWidget(self.button_pm, 8, 0, 1, 1)
        self.button8 = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button8.sizePolicy().hasHeightForWidth())
        self.button8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button8.setFont(font)
        self.button8.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button8.setObjectName("button8")
        self.gridLayout_2.addWidget(self.button8, 5, 1, 1, 1)
        self.button_div = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_div.sizePolicy().hasHeightForWidth())
        self.button_div.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_div.setFont(font)
        self.button_div.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_div.setObjectName("button_div")
        self.gridLayout_2.addWidget(self.button_div, 4, 3, 1, 1)
        self.button_del = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_del.sizePolicy().hasHeightForWidth())
        self.button_del.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_del.setFont(font)
        self.button_del.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_del.setObjectName("button_del")
        self.gridLayout_2.addWidget(self.button_del, 3, 3, 1, 1)
        self.button9 = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button9.sizePolicy().hasHeightForWidth())
        self.button9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button9.setFont(font)
        self.button9.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button9.setObjectName("button9")
        self.gridLayout_2.addWidget(self.button9, 5, 2, 1, 1)
        self.button_mul = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_mul.sizePolicy().hasHeightForWidth())
        self.button_mul.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_mul.setFont(font)
        self.button_mul.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_mul.setObjectName("button_mul")
        self.gridLayout_2.addWidget(self.button_mul, 5, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: #2B2B2B;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 12px;\n"
"    font-size: 24px;\n"
"}")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 4)
        self.button_cleare = QtWidgets.QPushButton(self.page3)
        self.button_cleare.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_cleare.sizePolicy().hasHeightForWidth())
        self.button_cleare.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_cleare.setFont(font)
        self.button_cleare.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_cleare.setAutoExclusive(False)
        self.button_cleare.setAutoDefault(False)
        self.button_cleare.setDefault(False)
        self.button_cleare.setFlat(False)
        self.button_cleare.setObjectName("button_cleare")
        self.gridLayout_2.addWidget(self.button_cleare, 3, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.page3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: #2B2B2B;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F4F4F;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #3A3F58;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid #4F4F4F;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down-arrow.png); /* Replace with your icon if desired */\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 1, 0, 1, 2)
        self.button_clear = QtWidgets.QPushButton(self.page3)
        self.button_clear.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clear.sizePolicy().hasHeightForWidth())
        self.button_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_clear.setFont(font)
        self.button_clear.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_clear.setObjectName("button_clear")
        self.gridLayout_2.addWidget(self.button_clear, 3, 2, 1, 1)
        self.button_percent = QtWidgets.QPushButton(self.page3)
        self.button_percent.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_percent.sizePolicy().hasHeightForWidth())
        self.button_percent.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_percent.setFont(font)
        self.button_percent.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_percent.setObjectName("button_percent")
        self.gridLayout_2.addWidget(self.button_percent, 4, 0, 1, 1)
        self.button_pow = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_pow.sizePolicy().hasHeightForWidth())
        self.button_pow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_pow.setFont(font)
        self.button_pow.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_pow.setObjectName("button_pow")
        self.gridLayout_2.addWidget(self.button_pow, 4, 1, 1, 1)
        self.button_sqrt = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_sqrt.sizePolicy().hasHeightForWidth())
        self.button_sqrt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_sqrt.setFont(font)
        self.button_sqrt.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_sqrt.setObjectName("button_sqrt")
        self.gridLayout_2.addWidget(self.button_sqrt, 4, 2, 1, 1)
        self.button7 = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button7.sizePolicy().hasHeightForWidth())
        self.button7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button7.setFont(font)
        self.button7.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button7.setObjectName("button7")
        self.gridLayout_2.addWidget(self.button7, 5, 0, 1, 1)
        self.button6 = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button6.sizePolicy().hasHeightForWidth())
        self.button6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button6.setFont(font)
        self.button6.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button6.setObjectName("button6")
        self.gridLayout_2.addWidget(self.button6, 6, 2, 1, 1)
        self.button_min = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_min.sizePolicy().hasHeightForWidth())
        self.button_min.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_min.setFont(font)
        self.button_min.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_min.setObjectName("button_min")
        self.gridLayout_2.addWidget(self.button_min, 6, 3, 1, 1)
        self.button1 = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button1.sizePolicy().hasHeightForWidth())
        self.button1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button1.setFont(font)
        self.button1.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button1.setObjectName("button1")
        self.gridLayout_2.addWidget(self.button1, 7, 0, 1, 1)
        self.button5 = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button5.sizePolicy().hasHeightForWidth())
        self.button5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button5.setFont(font)
        self.button5.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button5.setObjectName("button5")
        self.gridLayout_2.addWidget(self.button5, 6, 1, 1, 1)
        self.button4 = QtWidgets.QPushButton(self.page3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button4.sizePolicy().hasHeightForWidth())
        self.button4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button4.setFont(font)
        self.button4.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button4.setObjectName("button4")
        self.gridLayout_2.addWidget(self.button4, 6, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.page3)
        self.page5 = QtWidgets.QWidget()
        self.page5.setStyleSheet("QWidget {\n"
"    background-color: #1E1E1E;  /* Charcoal dark */\n"
"    color: #FFFFFF;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 16px;\n"
"}")
        self.page5.setObjectName("page5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 11, 0, 1, 5)
        self.comboBox_3 = QtWidgets.QComboBox(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    background-color: #2B2B2B;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F4F4F;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #3A3F58;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid #4F4F4F;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down-arrow.png); /* Replace with your icon if desired */\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_3, 0, 0, 1, 3)
        self.orderlabel = QtWidgets.QLabel(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.orderlabel.setFont(font)
        self.orderlabel.setObjectName("orderlabel")
        self.gridLayout_4.addWidget(self.orderlabel, 1, 4, 1, 1)
        self.orderbox = QtWidgets.QComboBox(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.orderbox.setFont(font)
        self.orderbox.setObjectName("orderbox")
        self.orderbox.addItem("")
        self.orderbox.addItem("")
        self.orderbox.addItem("")
        self.orderbox.addItem("")
        self.orderbox.addItem("")
        self.orderbox.addItem("")
        self.orderbox.addItem("")
        self.gridLayout_4.addWidget(self.orderbox, 1, 5, 1, 2)
        self.datatable = QtWidgets.QTableWidget(self.page5)
        self.datatable.setStyleSheet("""
            QHeaderView::section {
                background-color: #2b2b2b;   /* dark gray background */
                color: white;                /* white text */
                padding: 4px;
                font-weight: bold;
                border: 1px solid #444;
            }
            QTableWidget {
                gridline-color: #444;
            }
""")
        self.datatable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

        self.datatable.setObjectName("datatable")
        self.datatable.setColumnCount(0)
        self.datatable.setRowCount(0)
        self.gridLayout_4.addWidget(self.datatable, 2, 0, 1, 7)
        self.rent = QtWidgets.QLabel(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.rent.setFont(font)
        self.rent.setObjectName("rent")
        self.gridLayout_4.addWidget(self.rent, 4, 0, 1, 1)
        self.rentedit = QtWidgets.QLineEdit(self.page5)
        self.rentedit.setObjectName("rentedit")
        self.gridLayout_4.addWidget(self.rentedit, 4, 2, 1, 2)
        self.ownlabel = QtWidgets.QLabel(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.ownlabel.setFont(font)
        self.ownlabel.setObjectName("ownlabel")
        self.gridLayout_4.addWidget(self.ownlabel, 4, 4, 1, 3)
        self.infolabel = QtWidgets.QLabel(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.infolabel.setFont(font)
        self.infolabel.setObjectName("infolabel")
        self.gridLayout_4.addWidget(self.infolabel, 3, 0, 1, 4)
        self.education = QtWidgets.QLabel(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.education.setFont(font)
        self.education.setObjectName("education")
        self.gridLayout_4.addWidget(self.education, 5, 0, 1, 2)
        self.educationedit = QtWidgets.QLineEdit(self.page5)
        self.educationedit.setObjectName("educationedit")
        self.gridLayout_4.addWidget(self.educationedit, 5, 2, 1, 2)
        self.radioyes = QtWidgets.QRadioButton(self.page5)
        self.radioyes.setObjectName("radioyes")
        self.gridLayout_4.addWidget(self.radioyes, 5, 4, 1, 2)
        self.food = QtWidgets.QLabel(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.food.setFont(font)
        self.food.setObjectName("food")
        self.gridLayout_4.addWidget(self.food, 6, 0, 1, 1)
        self.r = QtWidgets.QRadioButton(self.page5)
        self.r.setObjectName("r")
        self.gridLayout_4.addWidget(self.r, 5, 6, 1, 1)
        self.entertainment = QtWidgets.QLabel(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.entertainment.setFont(font)
        self.entertainment.setObjectName("entertainment")
        self.gridLayout_4.addWidget(self.entertainment, 8, 0, 1, 2)
        self.clothing = QtWidgets.QLabel(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.clothing.setFont(font)
        self.clothing.setObjectName("clothing")
        self.gridLayout_4.addWidget(self.clothing, 7, 0, 1, 1)
        self.debtedit = QtWidgets.QLineEdit(self.page5)
        self.debtedit.setObjectName("debtedit")
        self.gridLayout_4.addWidget(self.debtedit, 9, 2, 1, 2)
        self.statisticbutton = QtWidgets.QPushButton(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.statisticbutton.setFont(font)
        self.statisticbutton.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.statisticbutton.setObjectName("statisticbutton")
        self.gridLayout_4.addWidget(self.statisticbutton, 13, 5, 1, 2)
        self.foodedit = QtWidgets.QLineEdit(self.page5)
        self.foodedit.setObjectName("foodedit")
        self.gridLayout_4.addWidget(self.foodedit, 6, 2, 1, 2)
        self.entertainmentedit = QtWidgets.QLineEdit(self.page5)
        self.entertainmentedit.setObjectName("entertainmentedit")
        self.gridLayout_4.addWidget(self.entertainmentedit, 8, 2, 1, 2)
        self.debt = QtWidgets.QLabel(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.debt.setFont(font)
        self.debt.setObjectName("debt")
        self.gridLayout_4.addWidget(self.debt, 9, 0, 1, 1)
        self.clothingedit = QtWidgets.QLineEdit(self.page5)
        self.clothingedit.setObjectName("clothingedit")
        self.gridLayout_4.addWidget(self.clothingedit, 7, 2, 1, 2)
        self.deletebutton = QtWidgets.QPushButton(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setItalic(False)
        self.deletebutton.setFont(font)
        self.deletebutton.setStyleSheet("QPushButton {\n"
"    background-color: #8b0000 ;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.deletebutton.setObjectName("deletebutton")
        self.gridLayout_4.addWidget(self.deletebutton, 12, 3, 1, 2)
        self.debt_2 = QtWidgets.QLabel(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.debt_2.setFont(font)
        self.debt_2.setObjectName("debt_2")
        self.gridLayout_4.addWidget(self.debt_2, 12, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 10, 0, 1, 1)
        self.idedit = QtWidgets.QLineEdit(self.page5)
        self.idedit.setObjectName("idedit")
        self.gridLayout_4.addWidget(self.idedit, 12, 1, 1, 2)
        self.registerbutton = QtWidgets.QPushButton(self.page5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.registerbutton.setFont(font)
        self.registerbutton.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.registerbutton.setObjectName("registerbutton")
        self.gridLayout_4.addWidget(self.registerbutton, 7, 4, 3, 3)
        self.stackedWidget.addWidget(self.page5)
        self.page4 = QtWidgets.QWidget()
        self.page4.setStyleSheet("QWidget {\n"
"    background-color: #1E1E1E;  /* Charcoal dark */\n"
"    color: #FFFFFF;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"    font-size: 16px;\n"
"}")
        self.page4.setObjectName("page4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem2)
        self.comboBox_2 = QtWidgets.QComboBox(self.page4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"    background-color: #2B2B2B;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F4F4F;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #3A3F58;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid #4F4F4F;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down-arrow.png); /* Replace with your icon if desired */\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.currency1 = QtWidgets.QComboBox(self.page4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.currency1.setFont(font)
        self.currency1.setStyleSheet("QComboBox {\n"
"    background-color: #2B2B2B;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F4F4F;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #3A3F58;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid #4F4F4F;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down-arrow.png); /* Replace with your icon if desired */\n"
"}")
        self.currency1.setObjectName("currency1")
        self.currency1.addItem("")
        self.currency1.addItem("")
        self.currency1.addItem("")
        self.currency1.addItem("")
        self.currency1.addItem("")
        self.currency1.addItem("")
        self.currency1.addItem("")
        self.verticalLayout.addWidget(self.currency1)
        self.converterin = QtWidgets.QLabel(self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.converterin.sizePolicy().hasHeightForWidth())
        self.converterin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.converterin.setFont(font)
        self.converterin.setStyleSheet("QLabel {\n"
"    background-color: #2B2B2B;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 12px;\n"
"    font-size: 24px;\n"
"}")
        self.converterin.setFrameShape(QtWidgets.QFrame.Box)
        self.converterin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.converterin.setObjectName("converterin")
        self.verticalLayout.addWidget(self.converterin)
        self.currency2 = QtWidgets.QComboBox(self.page4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.currency2.setFont(font)
        self.currency2.setStyleSheet("QComboBox {\n"
"    background-color: #2B2B2B;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F4F4F;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #3A3F58;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 1px solid #4F4F4F;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down-arrow.png); /* Replace with your icon if desired */\n"
"}")
        self.currency2.setObjectName("currency2")
        self.currency2.addItem("")
        self.currency2.addItem("")
        self.currency2.addItem("")
        self.currency2.addItem("")
        self.currency2.addItem("")
        self.currency2.addItem("")
        self.currency2.addItem("")
        self.verticalLayout.addWidget(self.currency2)
        self.converterout = QtWidgets.QLabel(self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.converterout.sizePolicy().hasHeightForWidth())
        self.converterout.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.converterout.setFont(font)
        self.converterout.setStyleSheet("QLabel {\n"
"    background-color: #2B2B2B;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 12px;\n"
"    font-size: 24px;\n"
"}")
        self.converterout.setFrameShape(QtWidgets.QFrame.Box)
        self.converterout.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.converterout.setObjectName("converterout")
        self.verticalLayout.addWidget(self.converterout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_clear_2 = QtWidgets.QPushButton(self.page4)
        self.button_clear_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clear_2.sizePolicy().hasHeightForWidth())
        self.button_clear_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.button_clear_2.setFont(font)
        self.button_clear_2.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_clear_2.setObjectName("button_clear_2")
        self.gridLayout_3.addWidget(self.button_clear_2, 0, 2, 1, 1)
        self.button7_2 = QtWidgets.QPushButton(self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button7_2.sizePolicy().hasHeightForWidth())
        self.button7_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button7_2.setFont(font)
        self.button7_2.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button7_2.setObjectName("button7_2")
        self.gridLayout_3.addWidget(self.button7_2, 1, 0, 1, 1)
        self.button8_2 = QtWidgets.QPushButton(self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button8_2.sizePolicy().hasHeightForWidth())
        self.button8_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button8_2.setFont(font)
        self.button8_2.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button8_2.setObjectName("button8_2")
        self.gridLayout_3.addWidget(self.button8_2, 1, 1, 1, 1)
        self.button9_2 = QtWidgets.QPushButton(self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button9_2.sizePolicy().hasHeightForWidth())
        self.button9_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button9_2.setFont(font)
        self.button9_2.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button9_2.setObjectName("button9_2")
        self.gridLayout_3.addWidget(self.button9_2, 1, 2, 1, 1)
        self.button4_2 = QtWidgets.QPushButton(self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button4_2.sizePolicy().hasHeightForWidth())
        self.button4_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button4_2.setFont(font)
        self.button4_2.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button4_2.setObjectName("button4_2")
        self.gridLayout_3.addWidget(self.button4_2, 2, 0, 1, 1)
        self.button5_2 = QtWidgets.QPushButton(self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button5_2.sizePolicy().hasHeightForWidth())
        self.button5_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button5_2.setFont(font)
        self.button5_2.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button5_2.setObjectName("button5_2")
        self.gridLayout_3.addWidget(self.button5_2, 2, 1, 1, 1)
        self.button6_2 = QtWidgets.QPushButton(self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button6_2.sizePolicy().hasHeightForWidth())
        self.button6_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.button6_2.setFont(font)
        self.button6_2.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button6_2.setObjectName("button6_2")
        self.gridLayout_3.addWidget(self.button6_2, 2, 2, 1, 1)
        self.button1_2 = QtWidgets.QPushButton(self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button1_2.sizePolicy().hasHeightForWidth())
        self.button1_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button1_2.setFont(font)
        self.button1_2.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button1_2.setObjectName("button1_2")
        self.gridLayout_3.addWidget(self.button1_2, 3, 0, 1, 1)
        self.button2_2 = QtWidgets.QPushButton(self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button2_2.sizePolicy().hasHeightForWidth())
        self.button2_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button2_2.setFont(font)
        self.button2_2.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button2_2.setObjectName("button2_2")
        self.gridLayout_3.addWidget(self.button2_2, 3, 1, 1, 1)
        self.button3_2 = QtWidgets.QPushButton(self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button3_2.sizePolicy().hasHeightForWidth())
        self.button3_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button3_2.setFont(font)
        self.button3_2.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button3_2.setObjectName("button3_2")
        self.gridLayout_3.addWidget(self.button3_2, 3, 2, 1, 1)
        self.button0_2 = QtWidgets.QPushButton(self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button0_2.sizePolicy().hasHeightForWidth())
        self.button0_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button0_2.setFont(font)
        self.button0_2.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button0_2.setObjectName("button0_2")
        self.gridLayout_3.addWidget(self.button0_2, 4, 1, 1, 1)
        self.button_flo_2 = QtWidgets.QPushButton(self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_flo_2.sizePolicy().hasHeightForWidth())
        self.button_flo_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.button_flo_2.setFont(font)
        self.button_flo_2.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.button_flo_2.setObjectName("button_flo_2")
        self.gridLayout_3.addWidget(self.button_flo_2, 4, 2, 1, 1)
        self.convertbutton = QtWidgets.QPushButton(self.page4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.convertbutton.sizePolicy().hasHeightForWidth())
        self.convertbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.convertbutton.setFont(font)
        self.convertbutton.setStyleSheet("QPushButton {\n"
"    background-color: #2D2D2D;\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #3A3A3A;\n"
"    border-radius: 10px;\n"
"    padding: 14px;\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"/* === Hover Effect === */\n"
"QPushButton:hover {\n"
"    background-color: #3A3F58;  /* Subtle bluish-gray */\n"
"    color: #FFFFFF;\n"
"    border: 1px solid #4F6C9D;\n"
"}\n"
"\n"
"/* === Pressed Effect === */\n"
"QPushButton:pressed {\n"
"    background-color: #0A84FF;  /* Deep blue feedback */\n"
"    color: #E0E0E0;\n"
"    padding-left: 13px;\n"
"    padding-top: 15px;\n"
"}")
        self.convertbutton.setObjectName("convertbutton")
        self.gridLayout_3.addWidget(self.convertbutton, 4, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.stackedWidget.addWidget(self.page4)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        Calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 507, 27))
        self.menubar.setObjectName("menubar")
        Calculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Calculator)
        self.statusbar.setObjectName("statusbar")
        Calculator.setStatusBar(self.statusbar)

        self.retranslateUi(Calculator)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "MainWindow"))
        self.button_flo.setText(_translate("Calculator", ","))
        self.button_equal.setText(_translate("Calculator", "="))
        self.button2.setText(_translate("Calculator", "2"))
        self.button_plus.setText(_translate("Calculator", "+"))
        self.button0.setText(_translate("Calculator", "0"))
        self.button3.setText(_translate("Calculator", "3"))
        self.button_pm.setText(_translate("Calculator", "+/-"))
        self.button8.setText(_translate("Calculator", "8"))
        self.button_div.setText(_translate("Calculator", "÷"))
        self.button_del.setText(_translate("Calculator", "⌫"))
        self.button9.setText(_translate("Calculator", "9"))
        self.button_mul.setText(_translate("Calculator", "×"))
        self.label.setText(_translate("Calculator", "0"))
        self.button_cleare.setText(_translate("Calculator", "CE"))
        self.comboBox.setItemText(0, _translate("Calculator", "Calculator"))
        self.comboBox.setItemText(1, _translate("Calculator", "Currency Converter"))
        self.comboBox.setItemText(2, _translate("Calculator", "Data"))
        self.button_clear.setText(_translate("Calculator", "C"))
        self.button_percent.setText(_translate("Calculator", "%"))
        self.button_pow.setText(_translate("Calculator", "xʸ"))
        self.button_sqrt.setText(_translate("Calculator", "ʸ√x"))
        self.button7.setText(_translate("Calculator", "7"))
        self.button6.setText(_translate("Calculator", "6"))
        self.button_min.setText(_translate("Calculator", "−"))
        self.button1.setText(_translate("Calculator", "1"))
        self.button5.setText(_translate("Calculator", "5"))
        self.button4.setText(_translate("Calculator", "4"))
        self.label_2.setText(_translate("Calculator", "Delete entry by ID:"))
        self.comboBox_3.setItemText(0, _translate("Calculator", "Data"))
        self.comboBox_3.setItemText(1, _translate("Calculator", "Calculator"))
        self.comboBox_3.setItemText(2, _translate("Calculator", "Currency Converter"))
        self.orderlabel.setText(_translate("Calculator", "Order by"))
        self.orderbox.setItemText(0, _translate("Calculator", "Id"))
        self.orderbox.setItemText(1, _translate("Calculator", "Rent"))
        self.orderbox.setItemText(2, _translate("Calculator", "Education"))
        self.orderbox.setItemText(3, _translate("Calculator", "Food"))
        self.orderbox.setItemText(4, _translate("Calculator", "Clothing"))
        self.orderbox.setItemText(5, _translate("Calculator", "Entertainment"))
        self.orderbox.setItemText(6, _translate("Calculator", "Debt"))
        self.rent.setText(_translate("Calculator", "Rent"))
        self.ownlabel.setText(_translate("Calculator", "Own apartment?"))
        self.infolabel.setText(_translate("Calculator", "Enter your info in USD$"))
        self.education.setText(_translate("Calculator", "Education"))
        self.radioyes.setText(_translate("Calculator", "Yes"))
        self.food.setText(_translate("Calculator", "Food"))
        self.r.setText(_translate("Calculator", "No"))
        self.entertainment.setText(_translate("Calculator", "Entertainment"))
        self.clothing.setText(_translate("Calculator", "Clothing"))
        self.statisticbutton.setText(_translate("Calculator", "Statistics"))
        self.debt.setText(_translate("Calculator", "Debt"))
        self.deletebutton.setText(_translate("Calculator", "DELETE"))
        self.debt_2.setText(_translate("Calculator", "ID"))
        self.registerbutton.setText(_translate("Calculator", "Register"))
        self.comboBox_2.setItemText(0, _translate("Calculator", "Currency Converter"))
        self.comboBox_2.setItemText(1, _translate("Calculator", "Data"))
        self.comboBox_2.setItemText(2, _translate("Calculator", "Calculator"))
        self.currency1.setItemText(0, _translate("Calculator", "USD $"))
        self.currency1.setItemText(1, _translate("Calculator", "EUR €"))
        self.currency1.setItemText(2, _translate("Calculator", "GEL ₾ "))
        self.currency1.setItemText(3, _translate("Calculator", "JPY ¥"))
        self.currency1.setItemText(4, _translate("Calculator", "GBP £"))
        self.currency1.setItemText(5, _translate("Calculator", "RUB ₽"))
        self.currency1.setItemText(6, _translate("Calculator", "CNY ¥"))
        self.converterin.setText(_translate("Calculator", "0"))
        self.currency2.setItemText(0, _translate("Calculator", "USD $"))
        self.currency2.setItemText(1, _translate("Calculator", "EUR €"))
        self.currency2.setItemText(2, _translate("Calculator", "GEL ₾ "))
        self.currency2.setItemText(3, _translate("Calculator", "JPY ¥"))
        self.currency2.setItemText(4, _translate("Calculator", "GBP £"))
        self.currency2.setItemText(5, _translate("Calculator", "RUB ₽"))
        self.currency2.setItemText(6, _translate("Calculator", "CNY ¥"))
        self.converterout.setText(_translate("Calculator", "0"))
        self.button_clear_2.setText(_translate("Calculator", "C"))
        self.button7_2.setText(_translate("Calculator", "7"))
        self.button8_2.setText(_translate("Calculator", "8"))
        self.button9_2.setText(_translate("Calculator", "9"))
        self.button4_2.setText(_translate("Calculator", "4"))
        self.button5_2.setText(_translate("Calculator", "5"))
        self.button6_2.setText(_translate("Calculator", "6"))
        self.button1_2.setText(_translate("Calculator", "1"))
        self.button2_2.setText(_translate("Calculator", "2"))
        self.button3_2.setText(_translate("Calculator", "3"))
        self.button0_2.setText(_translate("Calculator", "0"))
        self.button_flo_2.setText(_translate("Calculator", ","))
        self.convertbutton.setText(_translate("Calculator", "Convert"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QMainWindow()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())
